using EShop.Domain.Exceptions;
using EShop.Domain.Repositories;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EShop.Application.Products.Commands;

public record CreateProductOptionCommand(
    Guid ProductId,
    string Title,
    bool HasImage) : IRequest<bool>;

internal class CreateProductOptionCommandHandler : IRequestHandler<CreateProductOptionCommand, bool>
{
    private readonly IProductRepository _productRepository;

    public CreateProductOptionCommandHandler(IProductRepository productRepository)
    {
        _productRepository = productRepository;
    }

    public async Task<bool> Handle(CreateProductOptionCommand request, CancellationToken cancellationToken)
    {
        var query = _productRepository.GetQueryableSet()
            .Include(p => p.Options)
            .Where(p => p.Id == request.ProductId);

        var product = await _productRepository.FirstOrDefaultAsync(query);

        if (product is null)
        {
            throw new NotFoundException($"Product with ID {request.ProductId} not found.");
        }

        // Note:
        // client-generated, EntityConfiguration use ValueGenerated.Never() and set Id in code
        // store-generated, EntityConfiguration use ValueGenerated.OnAdd() and Id is generated by database

        product.AddOption(request.Title, request.HasImage);

        await _productRepository.UpdateAsync(product, cancellationToken);

        return await _productRepository.UnitOfWork.SaveEntitiesAsync(cancellationToken);
    }
}

public class CreateProductOptionCommandValidator : AbstractValidator<CreateProductOptionCommand>
{
    public CreateProductOptionCommandValidator()
    {
        RuleFor(x => x.ProductId)
            .NotEmpty().WithMessage("ProductId is required.");

        RuleFor(x => x.Title)
            .NotEmpty().WithMessage("Title is required.")
            .MaximumLength(255).WithMessage("Title must not exceed 255 characters.");
    }
}