export const ACTION_TYPE = {
  ADD_OPTION: "ADD_OPTION",
  UPDATE_OPTION: "UPDATE_OPTION",
  DELETE_OPTION: "DELETE_OPTION",
  ADD_OPTION_VALUE: "ADD_OPTION_VALUE",
  UPDATE_OPTION_VALUE: "UPDATE_OPTION_VALUE",
  DELETE_OPTION_VALUE: "DELETE_OPTION_VALUE",
};
